### ISSUE TITLE
GoogleSearch example not working

### ISSUE THREAD

**Issue by sagiavinash** [umaar/webdriverjs-recipes#12]
running `node GoogleSearch.js` leaves the following console output

```
Something went wrong
 Error: Wait timed out after 2058ms
    at <path>/webdriverjs-recipes/node_modules/selenium-webdriver/lib/webdriver/promise.js:1311:29
    at <path>/webdriverjs-recipes/node_modules/selenium-webdriver/lib/goog/base.js:1243:15
    at <path>/webdriverjs-recipes/node_modules/selenium-webdriver/lib/webdriver/promise.js:1539:20)
    at notify (<path>/webdriverjs-recipes/node_modules/selenium-webdriver/lib/webdriver/promise.js:362:12)
    at then (<path>/webdriverjs-recipes/node_modules/selenium-webdriver/lib/webdriver/promise.js:414:7)
    at Object.webdriver.promise.asap (<path>/webdriverjs-recipes/node_modules/selenium-webdriver/lib/webdriver/promise.js:662:11)
    at <path>/webdriverjs-recipes/node_modules/selenium-webdriver/lib/webdriver/promise.js:1555:25
    at <path>/webdriverjs-recipes/node_modules/selenium-webdriver/lib/goog/base.js:1243:15
    at webdriver.promise.ControlFlow.runInNewFrame_ (<path>/webdriverjs-recipes/node_modules/selenium-webdriver/lib/webdriver/promise.js:1539:20)
    at notify (<path>/webdriverjs-recipes/node_modules/selenium-webdriver/lib/webdriver/promise.js:362:12)
==== async task ====
    at webdriver.promise.ControlFlow.wait (/<path>/webdriverjs-recipes/node_modules/selenium-webdriver/lib/webdriver/promise.js:1296:15)
    at webdriver.WebDriver.wait (<path>/webdriverjs-recipes/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:543:21)
    at Object.<anonymous> (<path>/webdriverjs-recipes/GoogleSearch.js:38:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
```

to debug i have placed console.logs in all functions, 
execution is upto `findTutsPlusLink` function.

**Comment by wjhurley** [comment]
@sagiavinash It looks like webdriver timed out waiting for the page to load. Try using either
`driver.manage().timeouts().implicitlyWait(defaultTimeOut);`
or
`driver.manage().timeouts().pageLoadTimeout(defaultTimeOut);`

**Comment by aalmeidatw** [comment]
This is same problem for me.

Change http://code.tutsplus.com/ to https://code.tutsplus.com in this line: https://github.com/umaar/webdriverjs-recipes/blob/master/GoogleSearch.js#L26
